### ISSUE TITLE
Free courses cannot be downloaded at the moment

### ISSUE THREAD

**Issue by bizmate** [markbrown4/egghead-downloader#4]
First of all thanks for the script
Just an obvious question. As free courses cannot be downloaded at the moment are you planning to add this feature?

**Comment by markbrown4** [comment]
Hey, the free courses did used to be available for download.  It seems the recent redesign has broken the scraper, will look at updating it.

**Comment by markbrown4** [comment]
Should be resolved in 1536bc2de32f6796be832c3d8edabf0753477015

**Comment by bizmate** [comment]
works great, thank you

**Comment by markbrown4** [comment]
No problemo :)
